/* Copyright (C) 2013-2026 TU Dortmund University
 * This file is part of LearnLib <https://learnlib.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.learnlib.oracle.equivalence.mealy;

import java.util.Collection;
import java.util.Objects;
import java.util.stream.Stream;

import de.learnlib.TestWordGenerator;
import de.learnlib.oracle.AdaptiveMembershipOracle;
import de.learnlib.oracle.EquivalenceOracle.MealyEquivalenceOracle;
import de.learnlib.query.AdaptiveQuery;
import de.learnlib.query.DefaultQuery;
import net.automatalib.automaton.transducer.MealyMachine;
import net.automatalib.word.Word;
import org.checkerframework.checker.nullness.qual.Nullable;

/**
 * This {@link MealyEquivalenceOracle} evaluates test words generated by the given {@link TestWordGenerator} on a
 * symbol-by-symbol basis (via the provided {@link AdaptiveMembershipOracle}) and returns a counterexample on the first
 * observed mismatch. It can be used to improve the symbol performance of equivalence oracles which tend to generate
 * long testing sequences.
 * <p>
 * Note that this implementation does not support query parallelization via batching, even if the provided
 * {@link AdaptiveMembershipOracle} does.
 *
 * @param <I>
 *         input symbol type
 * @param <O>
 *         output symbol type
 */
public class EarlyExitEQOracle<I, O> implements MealyEquivalenceOracle<I, O> {

    private final AdaptiveMembershipOracle<I, O> oracle;
    private final TestWordGenerator<? super MealyMachine<?, I, ?, O>, I> delegate;

    public EarlyExitEQOracle(AdaptiveMembershipOracle<I, O> oracle,
                             TestWordGenerator<? super MealyMachine<?, I, ?, O>, I> delegate) {
        this.oracle = oracle;
        this.delegate = delegate;
    }

    @Override
    public @Nullable DefaultQuery<I, Word<O>> findCounterExample(MealyMachine<?, I, ?, O> hypothesis,
                                                                 Collection<? extends I> inputs) {

        final Stream<Word<I>> testWords = delegate.generateTestWords(hypothesis, inputs);
        final QueryWrapper<?, I, ?, O> wrapper = testWords.map(w -> new QueryWrapper<>(hypothesis, w))
                                                          .peek(oracle::processQuery)
                                                          .filter(QueryWrapper::hasMismatch)
                                                          .findFirst()
                                                          .orElse(null);
        return wrapper == null ? null : wrapper.buildQuery();
    }

    private static final class QueryWrapper<S, I, T, O> implements AdaptiveQuery<I, O> {

        private final MealyMachine<S, I, T, O> hypothesis;
        private final Word<I> input;

        private int currSymIdx;
        private @Nullable S currState;
        private boolean hasMismatch;
        private O mismatchOutput;

        QueryWrapper(MealyMachine<S, I, T, O> hypothesis, Word<I> input) {
            this.hypothesis = hypothesis;
            this.input = input;
            this.currState = hypothesis.getInitialState();
            this.currSymIdx = 0;
        }

        @Override
        public I getInput() {
            return input.getSymbol(currSymIdx);
        }

        @Override
        public Response processOutput(O out) {
            if (currState == null) {
                return handleError(out);
            }

            final T t = this.hypothesis.getTransition(currState, getInput());

            if (t == null) {
                return handleError(out);
            } else {
                final O hypOut = this.hypothesis.getTransitionOutput(t);
                if (Objects.equals(out, hypOut)) {
                    this.currState = this.hypothesis.getSuccessor(t);
                    this.currSymIdx++;
                    return this.currSymIdx == input.length() ? Response.FINISHED : Response.SYMBOL;
                } else {
                    return handleError(out);
                }
            }
        }

        Response handleError(O out) {
            this.hasMismatch = true;
            this.mismatchOutput = out;
            return Response.FINISHED;
        }

        boolean hasMismatch() {
            return hasMismatch;
        }

        DefaultQuery<I, Word<O>> buildQuery() {
            return new DefaultQuery<>(this.input.prefix(currSymIdx),
                                      Word.fromLetter(this.input.getSymbol(currSymIdx)),
                                      Word.fromLetter(mismatchOutput));
        }
    }
}
