# Copyright (C) 2013-2026 TU Dortmund University
# This file is part of LearnLib <https://learnlib.de>.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

app.version=${project.version}

option.args=Additional arguments to pass to the SUL.
option.cache=Use a query cache.
option.delim=The string used to split responses of the SUL into individual output symbols.
option.eqo=The strategy to search for counterexamples. Use repeatedly to build a chain of equivalence oracles. Strategies can be parameterized via the specific '--eqo-*' flags. Possible values are: ${COMPLETION-CANDIDATES}.
option.format=The output format to use for printing the final hypothesis model. Possible values are: ${COMPLETION-CANDIDATES}.
option.learner=The learning algorithm to use. Possible values are: ${COMPLETION-CANDIDATES}.
option.output=The output file to write the final hypothesis model to.
option.reset=Specifies the reset symbol. If provided, the SUL will be treated as 'stateful' which results in query symbols being applied one-by-one in subsequent invocations. The reset symbol will be used to reset the application state between queries.
option.stats=Enable the collection of statistics which will be printed at the end of the learning process.
option.stdin=Apply query symbols via standard-in as opposed to argument lists to the SUL.
option.sul=The path to the SUL used for answering queries.
option.type=The model type to infer. Possible values are: ${COMPLETION-CANDIDATES}.
option.verbose=Increase verbosity. Each repetition increases the log level from (initially) INFO to DEBUG to TRACE.

param.eqo.heading=%nParameters for equivalence oracles:%n

param.eqo.kway-s.k=The 'k' parameter of the 'KWayStateCoverEQOracle'.
param.eqo.kway-s.randomWalkLen=The 'randomWalkLen' parameter of the 'KWayStateCoverEQOracle'.
param.eqo.kway-s.combinationMethod=The 'combinationMethod' parameter of the 'KWayStateCoverEQOracle'. Possible values are: ${COMPLETION-CANDIDATES}.
param.eqo.kway-s.seed=The seed of the 'random' parameter of the 'KWayStateCoverEQOracle'.

param.eqo.kway-t.k=The 'k' parameter of the 'KWayTransitionCoverEQOracle'.
param.eqo.kway-t.randomWalkLen=The 'randomWalkLen' parameter of the 'KWayTransitionCoverEQOracle'.
param.eqo.kway-t.generationMethod=The 'generationMethod' parameter of the 'KWayTransitionCoverEQOracle'. Possible values are: ${COMPLETION-CANDIDATES}.
param.eqo.kway-t.optimizationMetric=The 'optimizationMetric' parameter of the 'KWayTransitionCoverEQOracle'. Possible values are: ${COMPLETION-CANDIDATES}.
param.eqo.kway-t.numGeneratePaths=The 'numGeneratePaths' parameter of the 'KWayTransitionCoverEQOracle'.
param.eqo.kway-t.maxPathLen=The 'maxPathLen' parameter of the 'KWayTransitionCoverEQOracle'.
param.eqo.kway-t.seed=The seed of the 'random' parameter of the 'KWayTransitionCoverEQOracle'.
param.eqo.kway-t.maxNumberOfSteps=The 'maxNumberOfSteps' parameter of the 'KWayTransitionCoverEQOracle'.

param.eqo.random-w.bound=The 'bound' parameter of the 'RandomWMethodEQOracle'.
param.eqo.random-w.rndLength=The 'rndLength' parameter of the 'RandomWMethodEQOracle'.
param.eqo.random-w.minimalSize=The 'minimalSize' parameter of the 'RandomWMethodEQOracle'.
param.eqo.random-w.seed=The seed of the 'random' parameter of the 'RandomWMethodEQOracle'.

param.eqo.random-wp.bound=The 'bound' parameter of the 'RandomWpMethodEQOracle'.
param.eqo.random-wp.rndLength=The 'rndLength' parameter of the 'RandomWpMethodEQOracle'.
param.eqo.random-wp.minimalSize=The 'minimalSize' parameter of the 'RandomWpMethodEQOracle'.
param.eqo.random-wp.seed=The seed of the 'random' parameter of the 'RandomWpMethodEQOracle'.

param.eqo.random.maxLength=The 'maxLength' parameter of the 'RandomWordsEQOracle'.
param.eqo.random.minLength=The 'minLength' parameter of the 'RandomWordsEQOracle'.
param.eqo.random.maxTests=The 'maxTests' parameter of the 'RandomWordsEQOracle'.
param.eqo.random.seed=The seed of the 'random' parameter of the 'RandomWordsEQOracle'.

param.eqo.sample=Provide an explicit trace that should be used for equivalence testing. Use repeatedly to provide multiple traces.
param.eqo.sample.split=The regexp to split and individual symbols of a trace.

param.eqo.w.expectedSize=The 'expectedSize' parameter for the 'WMethodEQOracle'.
param.eqo.w.lookahead=The 'lookahead' parameter for the 'WMethodEQOracle'.

param.eqo.wp.expectedSize=The 'expectedSize' parameter for the 'WpMethodEQOracle'.
param.eqo.wp.lookahead=The 'lookahead' parameter for the 'WpMethodEQOracle'.

param.symbol.cf.call.description=Define a call symbol. Use repeatedly to define multiple symbols.
param.symbol.cf.heading=%nSymbol definitions for learning context-free systems:%n
param.symbol.cf.int.description=Define an internal symbol. Use repeatedly to define multiple symbols.
param.symbol.cf.ret.description=Define a return symbol. Use repeatedly to define multiple symbols.
param.symbol.reg.description=Define an input symbol. Use repeatedly to define multiple symbols.
param.symbol.reg.heading=%nSymbol definitions for learning regular systems:%n
